jvm_binary(
  name = 'learn',
  source = 'LearnJava.java',
  main = 'com.pminkov.learnjava.LearnJava',
)

jvm_binary(
  name = 'visitor',
  source = 'VisitorPattern.java',
  main = 'com.pminkov.learnjava.VisitorPattern',
)

