jvm_binary(
    source = 'Search.java',
    main = 'com.pminkov.search.Search',
    dependencies = [
        'learnjava/3rdparty/jvm:lucene-core',
        'learnjava/3rdparty/jvm:lucene-queryparser']
)
