jvm_binary(
  main = 'com.pminkov.tryguice.TryGuice',
  dependencies = [
    ':try-guice'
  ]
)

java_library(
  name = "try-guice",
  sources = globs("*.java"),
  dependencies = [
    '3rdparty/jvm:guice-google'
  ]
)

