jvm_binary(
    source = 'Search.java',
    main = 'com.pminkov.search.Search',
    dependencies = [
        'search/3rdparty/jvm:lucene-core',
        'search/3rdparty/jvm:lucene-queryparser',
        'search/3rdparty/jvm:lucene-analyzers-common'
    ]
)
